{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.uten2c",
    "module": "flash",
    "version": "1.19.2+build.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "flash-1.19.2+build.1.jar",
          "url": "flash-1.19.2+build.1.jar",
          "size": 69658,
          "sha512": "81a4215ca78ee51f7e289bc592173326335227a68ef36348f5cb6e1589ff3a52400a97a46e6034367b9d3949bfd5e56b6fb81e3c660966fe853c96546d771900",
          "sha256": "63e4c58d7bdf31963e57cf0e032f10a61b8e5c19c67d4a61a0a05cdacd65da27",
          "sha1": "f0cd3f92b8d266b69040643c148914e8b52563f5",
          "md5": "993120b77c5452fd1e2a06b69a44b539"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.6.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor-jvm",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core-jvm",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu-jvm",
          "version": {
            "requires": "0.18.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime-jvm",
          "version": {
            "requires": "0.4.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "13.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.8.3+kotlin.1.7.10"
          }
        },
        {
          "group": "dev.uten2c",
          "module": "strobo",
          "version": {
            "requires": "1.19.2+build.3"
          }
        }
      ],
      "files": [
        {
          "name": "flash-1.19.2+build.1.jar",
          "url": "flash-1.19.2+build.1.jar",
          "size": 69658,
          "sha512": "81a4215ca78ee51f7e289bc592173326335227a68ef36348f5cb6e1589ff3a52400a97a46e6034367b9d3949bfd5e56b6fb81e3c660966fe853c96546d771900",
          "sha256": "63e4c58d7bdf31963e57cf0e032f10a61b8e5c19c67d4a61a0a05cdacd65da27",
          "sha1": "f0cd3f92b8d266b69040643c148914e8b52563f5",
          "md5": "993120b77c5452fd1e2a06b69a44b539"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flash-1.19.2+build.1-sources.jar",
          "url": "flash-1.19.2+build.1-sources.jar",
          "size": 13366,
          "sha512": "4b0a2946c19b07b9f2c65619aebdb467273937cf24607c9a169d7b0a54f0155ffaceeb7fa06884e9becadbdd871d62c91d408995fd6bfd1ebbc4a7cf52aa24b6",
          "sha256": "b0ad0c7957e9eaf54b50e71f38c912556a1c069b00d7a8344d66ad0a9959d164",
          "sha1": "ed44f62902e46529d5bebec89ca6658dc8276700",
          "md5": "4d00513ac14cad85c84de6183074d9f0"
        }
      ]
    }
  ]
}
