{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.uten2c",
    "module": "strobo",
    "version": "63",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "strobo-63.jar",
          "url": "strobo-63.jar",
          "size": 471385,
          "sha512": "be8e5d6be106bd3b59bf3df7fcb7c4f54992ffbb8e3cef3c4433fa6dd80906930e975c46f4a7ef44a354c4b4b53b051c5d2c2133e845ad564d13a2f6bcc12709",
          "sha256": "5747cd11c8cde746a2b7c645d1663716937713e771238a118dd43acc51a48197",
          "sha1": "c8406124279de24aa69f0a3dc739866f9e3b5891",
          "md5": "696e052ec23f019a7b04d56aa4b56c7b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.5.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.5.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor-jvm",
          "version": {
            "requires": "1.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core-jvm",
          "version": {
            "requires": "1.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "13.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.12.12"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.7.1+kotlin.1.6.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api-base",
          "version": {
            "requires": "0.4.1+b4f4f6cd65"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-resource-loader-v0",
          "version": {
            "requires": "0.4.11+3ac43d9565"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-gametest-api-v1",
          "version": {
            "requires": "1.0.7+c5d03bcd65"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-registry-sync-v0",
          "version": {
            "requires": "0.9.0+befed49e65"
          }
        }
      ],
      "files": [
        {
          "name": "strobo-63.jar",
          "url": "strobo-63.jar",
          "size": 471385,
          "sha512": "be8e5d6be106bd3b59bf3df7fcb7c4f54992ffbb8e3cef3c4433fa6dd80906930e975c46f4a7ef44a354c4b4b53b051c5d2c2133e845ad564d13a2f6bcc12709",
          "sha256": "5747cd11c8cde746a2b7c645d1663716937713e771238a118dd43acc51a48197",
          "sha1": "c8406124279de24aa69f0a3dc739866f9e3b5891",
          "md5": "696e052ec23f019a7b04d56aa4b56c7b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "strobo-63-sources.jar",
          "url": "strobo-63-sources.jar",
          "size": 68192,
          "sha512": "40ae3a4629d681359733d0e9a501330ff9796f36b9789bc504d10067d7769be762acc9eea8541d5a64f109bf4a8a30ade39336516d5295e15b4518fc885a7030",
          "sha256": "ab9fa8e3c5c5620dd0b1b7844dcddfffe1af6e8053e80b503c71374c72329a67",
          "sha1": "8bbbbe5cc5ce0cc610334e6739d9a2e256e3a575",
          "md5": "0a3b77790616a9e494a446fad91a7ed7"
        }
      ]
    }
  ]
}
