{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.uten2c",
    "module": "strobo",
    "version": "1.19+build.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "strobo-1.19+build.3.jar",
          "url": "strobo-1.19+build.3.jar",
          "size": 517727,
          "sha512": "ff95cbcd54abb941d3f4109672c4c0a2d0e8aac45eea46cc89646e5f7fe26179299e42b54a2483dca924d9ea43ce9dfe252afd6c9cabdef5b1f40582469f22fb",
          "sha256": "47817527cf634822d2fa45e49921b736d3d6998bbd07918e5c8c5cbb71e8a4be",
          "sha1": "f6b57e0324b62c6e9acb8a6c663a4576cdfbdd0c",
          "md5": "aeb60ef5955d5816994184151cf0699e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.6.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.3.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor-jvm",
          "version": {
            "requires": "1.3.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core-jvm",
          "version": {
            "requires": "1.3.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu-jvm",
          "version": {
            "requires": "0.17.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime-jvm",
          "version": {
            "requires": "0.3.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "13.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.6"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.8.0+kotlin.1.7.0"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api-base",
          "version": {
            "requires": "0.4.8+e62f51a3a9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-resource-loader-v0",
          "version": {
            "requires": "0.5.2+9e7660c6a9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-gametest-api-v1",
          "version": {
            "requires": "1.0.29+e62f51a3a9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-registry-sync-v0",
          "version": {
            "requires": "0.9.15+92cf9a3ea9"
          }
        }
      ],
      "files": [
        {
          "name": "strobo-1.19+build.3.jar",
          "url": "strobo-1.19+build.3.jar",
          "size": 517727,
          "sha512": "ff95cbcd54abb941d3f4109672c4c0a2d0e8aac45eea46cc89646e5f7fe26179299e42b54a2483dca924d9ea43ce9dfe252afd6c9cabdef5b1f40582469f22fb",
          "sha256": "47817527cf634822d2fa45e49921b736d3d6998bbd07918e5c8c5cbb71e8a4be",
          "sha1": "f6b57e0324b62c6e9acb8a6c663a4576cdfbdd0c",
          "md5": "aeb60ef5955d5816994184151cf0699e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "strobo-1.19+build.3-sources.jar",
          "url": "strobo-1.19+build.3-sources.jar",
          "size": 73175,
          "sha512": "0383cf7a0d6e490339f5ee9b9c39c8066fa9c19a9dfe50af118b7ec4fddbb448e5f647b5209032bf28887bb67ec8d29d99af12030afa5a0d79f9dbcfc2e536d2",
          "sha256": "2cee849e3442ee87474eb92d0605c2cb4e5f905868e1a32d259d8eaf4af24479",
          "sha1": "bc9caf3367bbc03c90de0d948746329e96909a7c",
          "md5": "219984f0718df9a2c15c19ef5e1fa32a"
        }
      ]
    }
  ]
}
