{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.uten2c",
    "module": "flash",
    "version": "1.19.2+build.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "flash-1.19.2+build.4.jar",
          "url": "flash-1.19.2+build.4.jar",
          "size": 83191,
          "sha512": "0a1c9fd8de96c3d2c68683f8a6e5df2d9b3be672a12702738cfb1afc190e273c2776ac4d529e143228e9883922040f697e7225a57a380279ebd1f81da64f93bf",
          "sha256": "92c90b696fb66e733533477233f7e3dc97883ed96e4a2a89c2f7fab1526514d5",
          "sha1": "15b9828b9a92a95b06efaba02e06551951ff07eb",
          "md5": "79950c5f217eacc73982a6fb79107b44"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.6.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor-jvm",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core-jvm",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu-jvm",
          "version": {
            "requires": "0.18.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime-jvm",
          "version": {
            "requires": "0.4.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "13.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.8.3+kotlin.1.7.10"
          }
        },
        {
          "group": "dev.uten2c",
          "module": "strobo",
          "version": {
            "requires": "1.19.2+build.4"
          }
        }
      ],
      "files": [
        {
          "name": "flash-1.19.2+build.4.jar",
          "url": "flash-1.19.2+build.4.jar",
          "size": 83191,
          "sha512": "0a1c9fd8de96c3d2c68683f8a6e5df2d9b3be672a12702738cfb1afc190e273c2776ac4d529e143228e9883922040f697e7225a57a380279ebd1f81da64f93bf",
          "sha256": "92c90b696fb66e733533477233f7e3dc97883ed96e4a2a89c2f7fab1526514d5",
          "sha1": "15b9828b9a92a95b06efaba02e06551951ff07eb",
          "md5": "79950c5f217eacc73982a6fb79107b44"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flash-1.19.2+build.4-sources.jar",
          "url": "flash-1.19.2+build.4-sources.jar",
          "size": 15161,
          "sha512": "c36b2795a0315ac6d4098b846f5a46715bbebb67c0eb4565d9f8dd26d5ddbe413b0a19371b20e1af9d4c95609a902b9a786c00b6a3849572d706490fe382b18c",
          "sha256": "554856b6c7a4610a32d7ce1839f9d887e89c14d4b6eade3fab7c8b8d391a679d",
          "sha1": "6730e0255163ad1313820f6ecc9596f417b3a163",
          "md5": "c76e2b71a8d3f5aaac0414540eadd64d"
        }
      ]
    }
  ]
}
