{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.uten2c",
    "module": "flash",
    "version": "1.19.2+build.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "flash-1.19.2+build.5.jar",
          "url": "flash-1.19.2+build.5.jar",
          "size": 83105,
          "sha512": "e307672bc29e2ecede88e3d5f5e4a33462dd133eddb7f2c2653db71ca6d194c160997fe870b6f8590bcedd6665a9f45f1b9b85fec507135cfb138da628a175b6",
          "sha256": "d9ac5d0ea5b894e48231a04d7d1b4b82ca9e9b47822083886c3c12d5b5fec9a9",
          "sha1": "cde04f02c882bc0a1395abe6d8fdd3732d668e34",
          "md5": "4b58b0fca5277eeff6afa70814b1ab61"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.6.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor-jvm",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core-jvm",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu-jvm",
          "version": {
            "requires": "0.18.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime-jvm",
          "version": {
            "requires": "0.4.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "13.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.8.3+kotlin.1.7.10"
          }
        },
        {
          "group": "dev.uten2c",
          "module": "strobo",
          "version": {
            "requires": "1.19.2+build.4"
          }
        }
      ],
      "files": [
        {
          "name": "flash-1.19.2+build.5.jar",
          "url": "flash-1.19.2+build.5.jar",
          "size": 83105,
          "sha512": "e307672bc29e2ecede88e3d5f5e4a33462dd133eddb7f2c2653db71ca6d194c160997fe870b6f8590bcedd6665a9f45f1b9b85fec507135cfb138da628a175b6",
          "sha256": "d9ac5d0ea5b894e48231a04d7d1b4b82ca9e9b47822083886c3c12d5b5fec9a9",
          "sha1": "cde04f02c882bc0a1395abe6d8fdd3732d668e34",
          "md5": "4b58b0fca5277eeff6afa70814b1ab61"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flash-1.19.2+build.5-sources.jar",
          "url": "flash-1.19.2+build.5-sources.jar",
          "size": 15139,
          "sha512": "764bb7f5206832eb0f52e6a53d410a046828e0c265f5e5afe6042ba63647b09a5f2293e89f2d5c33fe6c91465de47430dd051f4618c99bf0a50c552c12a5630f",
          "sha256": "623f4ae142dabc7185cb7c7adf24d0a1988fd744f7af8948bb86f3c7401ec089",
          "sha1": "85d3b2b3ceef43f4e332a6ad1ec0013771814946",
          "md5": "6173f3285afa8951555e477a143a11be"
        }
      ]
    }
  ]
}
