{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.uten2c",
    "module": "cmdlib",
    "version": "1.16.5+1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "i5n5yxkdovexhon5fo6cxkrlja"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "cmdlib-1.16.5+1.jar",
          "url": "cmdlib-1.16.5+1.jar",
          "size": 22458,
          "sha512": "53e1cc4451454a7a3c83f598e5cba2d605b014e42ca54cf736433973eb8ffae93e42623887daa2cc396f660e0bcda4df979685cc66424c1cc217d89658ddc3ab",
          "sha256": "5cdd108e3c3066f17dd9e02363f122ab900a91810d1d576a3294b1db0d9a2495",
          "sha1": "e8bf6499261c87978f6ac96a0564bdaa34e21e1b",
          "md5": "61426712fe81c534bbc2ccce18223aac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.destroystokyo.paper",
          "module": "paper-api",
          "version": {
            "requires": "1.16.5-R0.1-SNAPSHOT"
          }
        },
        {
          "group": "com.destroystokyo.paper",
          "module": "paper",
          "version": {
            "requires": "1.16.5-R0.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "cmdlib-1.16.5+1.jar",
          "url": "cmdlib-1.16.5+1.jar",
          "size": 22458,
          "sha512": "53e1cc4451454a7a3c83f598e5cba2d605b014e42ca54cf736433973eb8ffae93e42623887daa2cc396f660e0bcda4df979685cc66424c1cc217d89658ddc3ab",
          "sha256": "5cdd108e3c3066f17dd9e02363f122ab900a91810d1d576a3294b1db0d9a2495",
          "sha1": "e8bf6499261c87978f6ac96a0564bdaa34e21e1b",
          "md5": "61426712fe81c534bbc2ccce18223aac"
        }
      ]
    }
  ]
}
