{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.uten2c",
    "module": "strobo",
    "version": "69",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "strobo-69.jar",
          "url": "strobo-69.jar",
          "size": 520823,
          "sha512": "f3fd17e95888ae1c6350ba815b87a4ff37559d609e3ffa544da308c183195d965cfe0b5b2f5e820519d0563f471d40305914c15cec4831dbed86e424b8177e06",
          "sha256": "49f92a722be9098a59aa3751c541ab75b8d7b0815bad8bb1b5a55eb5b8d66305",
          "sha1": "9ebd905b6e3bb33c3868766e1e59ac68d742128a",
          "md5": "bfea0b7d1e1699f6bae25c9f085e8ca3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.5.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.5.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor-jvm",
          "version": {
            "requires": "1.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core-jvm",
          "version": {
            "requires": "1.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "13.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.13.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.7.1+kotlin.1.6.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api-base",
          "version": {
            "requires": "0.4.4+d7c144a860"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-resource-loader-v0",
          "version": {
            "requires": "0.4.18+2de5574560"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-gametest-api-v1",
          "version": {
            "requires": "1.0.15+2540745460"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-registry-sync-v0",
          "version": {
            "requires": "0.9.8+0d9ab37260"
          }
        }
      ],
      "files": [
        {
          "name": "strobo-69.jar",
          "url": "strobo-69.jar",
          "size": 520823,
          "sha512": "f3fd17e95888ae1c6350ba815b87a4ff37559d609e3ffa544da308c183195d965cfe0b5b2f5e820519d0563f471d40305914c15cec4831dbed86e424b8177e06",
          "sha256": "49f92a722be9098a59aa3751c541ab75b8d7b0815bad8bb1b5a55eb5b8d66305",
          "sha1": "9ebd905b6e3bb33c3868766e1e59ac68d742128a",
          "md5": "bfea0b7d1e1699f6bae25c9f085e8ca3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "strobo-69-sources.jar",
          "url": "strobo-69-sources.jar",
          "size": 82313,
          "sha512": "03849e4e9fe33f0ee02b259bbf4a1698881e465a52e37f5d002adcb78a49cc7e103b5fbb7255f22ace4ce2c5ae81eaf703dd004332b93ecc82997bd4929cef17",
          "sha256": "91aafebb35ce81dc504ea320531b18f23df9f125c35842767af0c877aa764ff9",
          "sha1": "04555cb89ed1a4ff6f48ade7a3dd3f76aacc9e76",
          "md5": "ae1f0a558fbf76fa1e90488bb65eefda"
        }
      ]
    }
  ]
}
