{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.uten2c",
    "module": "flash",
    "version": "1.19.2+build.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "flash-1.19.2+build.3.jar",
          "url": "flash-1.19.2+build.3.jar",
          "size": 82343,
          "sha512": "efb5f6cc44d4f63f049db3460bfb8da4b34e5aa612e297d2a984cd4c765606b8cbc1b13485f7737e11cdd87ab68c51c8309e23fb0189e837c189a2181aa6db46",
          "sha256": "f4ca1527ddeccc9c8fb45be4c0412fcc7c37f60854c954cd9ce4a9b988d4af82",
          "sha1": "d6349c67df103c84c57fc4d3a6973109e0b617da",
          "md5": "8a3f1e148195e7d1f937137988beb213"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.6.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor-jvm",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core-jvm",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu-jvm",
          "version": {
            "requires": "0.18.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime-jvm",
          "version": {
            "requires": "0.4.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "13.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.8.3+kotlin.1.7.10"
          }
        },
        {
          "group": "dev.uten2c",
          "module": "strobo",
          "version": {
            "requires": "1.19.2+build.4"
          }
        }
      ],
      "files": [
        {
          "name": "flash-1.19.2+build.3.jar",
          "url": "flash-1.19.2+build.3.jar",
          "size": 82343,
          "sha512": "efb5f6cc44d4f63f049db3460bfb8da4b34e5aa612e297d2a984cd4c765606b8cbc1b13485f7737e11cdd87ab68c51c8309e23fb0189e837c189a2181aa6db46",
          "sha256": "f4ca1527ddeccc9c8fb45be4c0412fcc7c37f60854c954cd9ce4a9b988d4af82",
          "sha1": "d6349c67df103c84c57fc4d3a6973109e0b617da",
          "md5": "8a3f1e148195e7d1f937137988beb213"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flash-1.19.2+build.3-sources.jar",
          "url": "flash-1.19.2+build.3-sources.jar",
          "size": 14784,
          "sha512": "c20b2234a9a41758cb7a674f7028df2e59c8e9120e5148933699e428060ff80af132cf892edf658000477912bd18755136a9ee6ba887085871aa408f03638ec4",
          "sha256": "8c1055a4039628afabaaf4a657451a4c16ee9ab16ba0aeeb02e4dbc89846c555",
          "sha1": "ef309aaefad145b5853309d6e117c1f3873b8a84",
          "md5": "19fd2ce1994bf989076f02fb8590b447"
        }
      ]
    }
  ]
}
