{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.uten2c",
    "module": "flash",
    "version": "1.19.2+build.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "flash-1.19.2+build.2.jar",
          "url": "flash-1.19.2+build.2.jar",
          "size": 82259,
          "sha512": "9581265df618361e3ecbf9551a728251529a702b3d55164b4e1a6014660548c7f069e7ed0dbdebd8bc55a0ba275a183e15711f56f7753cc1830ce1415fded9bb",
          "sha256": "e9f1bcdc3a33fefa8108d98ed40a9f521f09bffd163e4c4cb358b32a30870bf1",
          "sha1": "65c733bccf0863249b36f0dc70e75f70a36425c8",
          "md5": "252ec6a838bdc78645c6831532202431"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.6.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor-jvm",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core-jvm",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu-jvm",
          "version": {
            "requires": "0.18.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime-jvm",
          "version": {
            "requires": "0.4.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "13.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.8.3+kotlin.1.7.10"
          }
        },
        {
          "group": "dev.uten2c",
          "module": "strobo",
          "version": {
            "requires": "1.19.2+build.4"
          }
        }
      ],
      "files": [
        {
          "name": "flash-1.19.2+build.2.jar",
          "url": "flash-1.19.2+build.2.jar",
          "size": 82259,
          "sha512": "9581265df618361e3ecbf9551a728251529a702b3d55164b4e1a6014660548c7f069e7ed0dbdebd8bc55a0ba275a183e15711f56f7753cc1830ce1415fded9bb",
          "sha256": "e9f1bcdc3a33fefa8108d98ed40a9f521f09bffd163e4c4cb358b32a30870bf1",
          "sha1": "65c733bccf0863249b36f0dc70e75f70a36425c8",
          "md5": "252ec6a838bdc78645c6831532202431"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flash-1.19.2+build.2-sources.jar",
          "url": "flash-1.19.2+build.2-sources.jar",
          "size": 14820,
          "sha512": "564104657fc5f245d0580756db80c3695e86b3b28e48c8d568bf86833d4eb838cacf8d28cb0de1d16a285f8b0321d3b97e45dc8dacd2d526419ac070e4acc4e2",
          "sha256": "9a8a663e3d186bdc59e088d8a8e97c10ef08ba348e4892d9c84602125e82a83a",
          "sha1": "ac2e5c5b9b53390e6ad8bdf8a028c2b7f50ba905",
          "md5": "b9b63bcca8c5c7d9933e16e1d67fd8e2"
        }
      ]
    }
  ]
}
